### ISSUE TITLE
possibility to prefetch_related?

### ISSUE THREAD

**Issue by tinnet** [seebass/drf-nested-fields#1]
Cool addon for DRF! We built something similar to `CustomFieldsMixin` in DRF2, but we had massive problems with the query count when embedding related fields. So first we added every possible field as a `prefetch_related` to the models queryset, but for more complex models that also caused a cascade of extra queries. We ended up building the queryset dynamically from the fields parameter. Have you encountered this issue and figured out a way around it? 

can't flag my issue as "question" myself, sorry for that :(

**Comment by seebass** [comment]
Thanks for your reply. Now that you mentioned it, I realized I forgot to take this optimization when extracting the lib from our project ;) See db021a8755decdda4ff32977b81c5ff63f3b55a7
But this should be pretty much the same way, you already build the dynamic queryset. Don't know exactly which way around it you have in mind.

**Comment by tinnet** [comment]
Nice, thanks :) I had no other way in mind, just wondering if you had found a magic solution by knowing DRF better ;)
